from utils import Group

subgroups= {'lc0a' : Group('lc0a','fi',{'lemma':('eilen',)},nextcond=['!token',('aamulla','illlalla','päivällä','aamusta','illasta','iltapäivällä','aamupäivällä','kello','kahdelta','kolmelta','neljältä','viideltä','kuudelta','seitsemältä','kahdeksalta','yhdeksältä','kymmeneltä','yhdeltätoista','kahdeltatoista','puoleltapäivin')],lengthmeter=[0,0]),
            'lc0b' : Group('lc0b','fi',{'lemma':('tänään',)},nextcond=['!token',('aamulla','illlalla','päivällä','aamusta','illasta','iltapäivällä','aamupäivällä','kello','kahdelta','kolmelta','neljältä','viideltä','kuudelta','seitsemältä','kahdeksalta','yhdeksältä','kymmeneltä','yhdeltätoista','kahdeltatoista','puoleltapäivin')],lengthmeter=[0,0]),
            'lc0c' : Group('lc0c','fi',{'lemma':('huomenna',)},nextcond=['!token',('aamulla','illlalla','päivällä','aamusta','illasta','iltapäivällä','aamupäivällä','kello','kahdelta','kolmelta','neljältä','viideltä','kuudelta','seitsemältä','kahdeksalta','yhdeksältä','kymmeneltä','yhdeltätoista','kahdeltatoista','puoleltapäivin')],lengthmeter=[0,0]),
            'lc1' : Group('lc1','fi',{'token':('viikolla', 'vuonna', 'päivinä', 'vuosina')},prevcond=['lemma',('viime',)],lengthmeter=[1,0]),
            'lc2' : Group('lc2','fi',{'token':('aamulla','illalla')}, prevcond=['!token',('Yhdeltä', 'Kahdelta', 'Kolmelta', 'Neljältä', 'Viideltä', 'Kuudelta', 'Seitsemältä', 'Kahdeksalta', 'Yhdeksältä', 'Kymmeneltä', 'Yhdeltätoista', 'Kahdeltatoista','Eilen','Tänään','Huomenna','Maanantaina','Tiistaina','Keskiviikkona','Torstaina','Perjantaina','Lauantaina','Sunnuntaina', 'yhdeltä', 'kahdelta', 'kolmelta', 'neljältä', 'viideltä', 'kuudelta', 'seitsemältä', 'kahdeksalta', 'yhdeksältä', 'kymmeneltä', 'yhdeltätoista', 'kahdeltatoista','eilen','tänään','huomenna','maanantaina','tiistaina','keskiviikkona','torstaina','perjantaina','lauantaina','sunnuntaina')],nextcond=['!token',('varhain', 'puoli', 'kello', 'klo', 'yhdeltä', 'kahdelta', 'kolmelta', 'neljältä', 'viideltä', 'kuudelta', 'seitsemältä', 'kahdeksalta', 'yhdeksältä', 'kymmeneltä', 'yhdeltätoista', 'kahdeltatoista','Yhdeltä', 'Kahdelta', 'Kolmelta', 'Neljältä', 'Viideltä', 'Kuudelta', 'Seitsemältä', 'Kahdeksalta', 'Yhdeksältä', 'Kymmeneltä', 'Yhdeltätoista', 'Kahdeltatoista','Eilen','Tänään','Huomenna','Maanantaina','Tiistaina','Keskiviikkona','Torstaina','Perjantaina','Lauantaina','Sunnuntaina')],secondpreviouscond=['!token',('kello','puoli','Puoli')],lengthmeter=[0,0]),
            'lc3' : Group('lc3','fi',{'token':('sodan',)},nextcond=['lemma',('jälkeen',)],lengthmeter=[0,1]),
            'lc4' : Group('lc4','fi',{'token':('siitä',)},nextcond=['token',('asti',)],lengthmeter=[0,1]),
            'lc5' : Group('lc5','fi',{'token':('vuoden', 'päivän', 'viikon', 'tunnin')},nextcond=['token',('päästä',)],lengthmeter=[0,1]),
            'lc6' : Group('lc6','fi',{'token':('kahdelta', 'kolmelta', 'neljältä', 'viideltä', 'kuudelta', 'seitsemältä', 'kahdeksalta', 'yhdeksältä', 'kymmeneltä', 'yhdeltätoista', 'kahdeltatoista')},prevcond=['!token',('kaikilta','niiltä','näiltä','meiltä','noilta','tänään','eilen','huomenna','toissapäivänä')],nextcond=['!feat',('Case=Abl|Number=Sing',)],lengthmeter=[0,0]),
            'lc7a' : Group('lc7a','fi',{'token':('aikaan',)}, prevcond=['token','siihen'], nextcond=['!token',('kun','jolloin')], countcomma=False,lengthmeter=[1,0]),
            'lc7b' : Group('lc7b','fi',{'token':('silloin',)},nextcond=['!token',('kun','jos')], countcomma=False,lengthmeter=[0,0]),
            'lc8' : Group('lc8','fi',{'token':('pian',)},prevcond=['!token',('niin','jos','')],nextcond=['!token',('kuin',)],secondnextcond=['!token',('jälkeen',)],lengthmeter=[0,0]),
            'lc9a' : Group('lc9a','fi',{'token':('nykyisin','nykyään')},nextcond=['!token',('jos','kun')], countcomma=False,lengthmeter=[0,0]),
            'lc9b' : Group('lc9b','fi',{'token':('nyt',)},nextcond=['!token',('jos','kun')], countcomma=False,lengthmeter=[0,0]),
            'lc10' : Group('lc10','fi',{'token':('tammikuusta', 'helmikuusta', 'maaliskuusta', 'huhtikuusta', 'toukokuusta', 'kesäkuusta', 'heinäkuusta', 'elokuusta', 'syyskuusta', 'lokakuusta', 'marraskuusta', 'joulukuusta')}, prevcond=['token',('vuoden',)], secondpreviouscond=['token',('tämän','viime','toissa')],lengthmeter=[2,0]),
            'lc11' : Group('lc11','fi',{'token':('vuonna',)}, nextcond=['#token','199.'],lengthmeter=[0,1]),
            'lc12' : Group('lc12','fi',{'token':('aamuna','päivänä','iltana')},prevcond=['token',('yhtenä',)],lengthmeter=[1,0]),
            'lc13' : Group('lc13','fi',{'token':('vuodesta',)},nextcond=['#token','19..'],secondnextcond=['!token',('vuoteen',)],lengthmeter=[0,1]),
            'lc15' : Group('lc15','fi',{'token':('hetkenä','hetkinä','hetkellä','hetkillä')},prevcond=['lemma',('sellainen','semmoinen','tuollainen','tällainen')],lengthmeter=[1,0]),
            'lc16' : Group('lc16','fi',{'token':('tiistaina','keskiviikkona','torstaina')},lengthmeter=[0,0]),
            'lc17' : Group('lc17','fi',{'token':('maaliskuussa','lokakuussa')},nextcond=['!token',('vuonna',)],lengthmeter=[0,0]),
            'fr1' : Group('fr1','fi',{'token':('päivä', 'viikko', 'vuosi', 'kuukausi')},prevcond=['token',('joka',)],lengthmeter=[1,0]),
            'fr2' : Group('fr2','fi',{'token':('maanantaisin', 'tiistaisin', 'keskiviikkoisin', 'torstaisin', 'perjantaisin', 'lauantaisin', 'sunnuntaisin')},lengthmeter=[0,0]),
            'fr3a' : Group('fr3a','fi',{'token':('kertaa',)},prevcond=['token',('2', '3', '4', '5', '6', '7', '8', '9', '10', 'kaksi', 'kolme', 'neljä', 'viisi', 'kuusi', 'seitsemän', 'kahdeksan', 'yhdeksän', 'kymmenen')],nextcond=['¤feat','.*Cmp.*'], secondnextcond=['!token',('kuin',)],lengthmeter=[1,0]),
            'fr3b' : Group('fr3b','fi',{'token':('kahdesti', 'kolmesti', 'neljästi', 'viidesti')},nextcond=['!token',('viikossa', 'päivässä', 'vuodessa', 'kuukaudessa', 'tunnissa', 'sekunnissa', 'aamussa', 'illassa',)],secondnextcond=['!token',('kuin',)],lengthmeter=[0,0]),
            'fr4a' : Group('fr4a','fi',{'token':('usein',)},lengthmeter=[0,0]),
            'fr4b' : Group('fr4b','fi',{'token':('aina',)},lengthmeter=[0,0]),
            'fr5a' : Group('fr5a','fi',{'token':('harvoin',)},lengthmeter=[0,0]),
            'fr5b' : Group('fr5b','fi',{'token':('joskus',)},lengthmeter=[0,0]),
            'fr6' : Group('fr6','fi',{'token':('tavallisesti','yleensä')},lengthmeter=[0,0]),
            'fr7' : Group('fr7','fi',{'token':('ajoittain',)},lengthmeter=[0,0]),
            'fr8' : Group('fr8','fi',{'token':('koskaan',)}, prevcond=['!token',('kuin',)],nextcond=['!token',('aiemmin','aikaisemmin','ennen')],countcomma=False,lengthmeter=[0,0]),
            'ex1' : Group('ex1','fi',{'token':('päivää', 'vuotta', 'viikkoa', 'tuntia')},prevcond=['token',('2', '3', '4', '5', '6', '7', '8', '9', '10', 'kaksi', 'kolme', 'neljä', 'viisi', 'kuusi', 'seitsemän', 'kahdeksan', 'yhdeksän', 'kymmenen')],nextcond=['!token',('sitten','')], secondnextcond=['!token',('ennen','jälkeen','kuluttua','päästä','perästä')],secondpreviouscond=['!token',('täyttää','täytti','täyttäisi','täyttänyt')],lengthmeter=[1,0]),
            'ex2a' : Group('ex2a','fi',{'token':('päivässä', 'vuodessa', 'viikossa', 'tunnissa')},prevcond=['token',('kahdessa', 'kolmessa', 'neljässä', 'viidessä', 'kuudessa', 'seitsemässä', 'kahdeksassa', 'yhdeksässä', 'kymmenessä','parissa','muutamassa')],lengthmeter=[1,0]),
            'ex2b' : Group('ex2b','fi',{'token':('ajassa',)},prevcond=['token',('siinä',)],lengthmeter=[1,0]),
            'ex3a' : Group('ex3a','fi',{'token':('aikana',)}, secondpreviouscond=['token',('viime', 'koko', 'sen', 'tuon')],lengthmeter=[2,0]),
            'ex3b' : Group('ex3b','fi',{'token':('kuluessa',)},prevcond=['token',('vuoden', 'viikon', 'kuukauden', 'kesän', 'kevään', 'syksyn', 'talven')],secondpreviouscond=['!token',('tämän', 'viime','koko','sen','tuon','2', '3', '4', '5', '6', '7', '8', '9', '10', 'parin','muutaman','yhden','kahden', 'kolmen', 'neljän', 'viiden', 'kuuden', 'seitsemän', 'kahdeksan', 'yhdeksän', 'kymmenenen')],lengthmeter=[1,0]),
            'ex4' : Group('ex4','fi',{'token':('kuukaudeksi', 'viikoksi', 'päiväksi', 'vuodeksi', 'tunniksi')},prevcond=['token',('2', '3', '4', '5', '6', '7', '8', '9', '10', 'kahdeksi', 'kolmeksi', 'neljäksi', 'viideksi', 'kuudeksi', 'seitsemäksi', 'kahdeksaksi', 'yhdeksäksi', 'kymmeneksi')],lengthmeter=[1,0]),
            'ex5a' : Group('ex5a','fi',{'token':('hetkessä',)},prevcond=['!token',('siinä','tuossa','tässä','samassa','tossa','sellasessa','sellaisessa')],lengthmeter=[0,0]),
            'ex5b' : Group('ex5b','fi',{'token':('äkkiä','yhtäkkiä','yht#äkkiä')},lengthmeter=[0,0]),
            'ex6' : Group('ex6','fi',{'token':('kauan',)}),
            'ex7' : Group('ex7','fi',{'token':('aikaan','aikoihin')},prevcond=['token',('pitkään','pitkiin')],lengthmeter=[1,0]),
            'ex8' : Group('ex8','fi',{'token':('aikaa',)},prevcond=['token',('jonkin','jonkun')],nextcond=['!token',('sitten','myöhemmin')],secondnextcond=['!token',('jälkeen','päästä','kuluttua','myöhemmin','mentyä','perästä')],lengthmeter=[1,0]),
            'ex9' : Group('ex9','fi',{'token':('viikon',)},nextcond=['!token',('päästä','jälkeen','kuluttua','myöhemmin','mentyä','perästä')], prevcond=[['!token','!pos','¤feat'],[['seuraavan','edellisen','muutaman','parin','yhden','kuluneen', 'koko', 'sen', 'minkä', 'viime', 'ensi', 'edellisen', 'yhden', 'toisen', 'tämän', 'kokonaisen', 'toissa'],['NUM'],'.*Gen.*']],lengthmeter=[0,0]),
            'ex10' : Group('ex10','fi',{'token':('viikon',)},prevcond=['token',('koko',)],secondpreviouscond=['!token',('voimassa',)],lengthmeter=[1,0]),
            'ex11' : Group('ex11','fi',{'token':('nopeasti',)},lengthmeter=[0,0]),
            'pr1' : Group('pr1','fi',{'token':('jo',)},lengthmeter=[0,0]),
            'pr2' : Group('pr2','fi',{'token':('vielä',)},lengthmeter=[0,0]),
            'pr3' : Group('pr3','fi',{'token':('enää',)},lengthmeter=[0,0]),
            'lm1' : Group('lm1','fi',{'token':('maissa','tienoilla','tietämillä','hujakoilla','paikkeilla')},lengthmeter=[1,0]),
           }


#https://korp.csc.fi/#?prequery_within=sentence&corpus=klk_fi_1990,ftc_aamu1995,ftc_aamu1999,ftc_demari1995,ftc_demari1997,ftc_demari1998,ftc_demari1999,ftc_hs1995rt,ftc_hysa1994,ftc_hasa1999,ftc_karj1993,ftc_karj1994,ftc_karj1995,ftc_karj1997,ftc_karj1998,ftc_karj1999,ftc_tusa1998,ftc_tusa1999,ftc_ilta1996,ftc_kaleva1998_1999,ftc_kangasa,ftc_kesu1999,reittidemo&cqp=%5B%5D&search_tab=2&hpp=1000&search=cqp%7C%5Bword%3D%22koskaan%22%20%25c%5D&page=2

